/****************************************************************************
 *
 * MODULE:       i.sar.interferometry
 * AUTHOR(S):    Yann Chemin <dr.yann.chemin gmail.com>
 * PURPOSE:      libsarunwrap: minimum cost flow phase unwrapping with
 *               statistical costs (after Costantini 1998 and SNAPHU, Chen
 *               and Zebker 2001). The per-pixel preparation (gradients,
 *               costs, residues) runs on the host (OpenMP) or on an OpenCL
 *               device; the network flow is solved on the host by
 *               successive shortest paths with node potentials.
 * COPYRIGHT:    (C) 2026 by Yann Chemin and the GRASS Development Team
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 *
 *****************************************************************************/

#define CL_TARGET_OPENCL_VERSION 120
#define CL_USE_DEPRECATED_OPENCL_1_2_APIS

#include <ctype.h>
#include <math.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <CL/cl.h>
#ifdef _OPENMP
#include <omp.h>
#endif

#include "sarunwrap.h"
#include "sarunwrap_core.h"

/* sarunwrap_core.h and sarunwrap_kernels.cl as one string literal,
 * generated by the Makefile. */
static const char *kernel_source =
#include "sarunwrap_cl.h"
    ;

static struct {
    int ready;
    int use_ocl;
    int nthreads;
    cl_context context;
    cl_command_queue queue;
    cl_program program;
    cl_kernel kernel;
} state;

static void set_msg(char *msg, int msglen, const char *fmt, ...)
{
    va_list ap;

    if (!msg || msglen <= 0)
        return;
    va_start(ap, fmt);
    vsnprintf(msg, (size_t)msglen, fmt, ap);
    va_end(ap);
}

static int contains_nocase(const char *hay, const char *needle)
{
    size_t n = strlen(needle), i, j;

    if (n == 0)
        return 1;
    for (i = 0; hay[i]; i++) {
        for (j = 0; j < n && hay[i + j]; j++)
            if (tolower((unsigned char)hay[i + j]) !=
                tolower((unsigned char)needle[j]))
                break;
        if (j == n)
            return 1;
    }
    return 0;
}

static void release_ocl(void)
{
    if (state.kernel)
        clReleaseKernel(state.kernel);
    if (state.program)
        clReleaseProgram(state.program);
    if (state.queue)
        clReleaseCommandQueue(state.queue);
    if (state.context)
        clReleaseContext(state.context);
    state.kernel = NULL;
    state.program = NULL;
    state.queue = NULL;
    state.context = NULL;
}

static int try_device(cl_platform_id platform, cl_device_id device, char *msg,
                      int msglen)
{
    cl_int err;
    size_t len = strlen(kernel_source);
    char name[256], pname[256];
    cl_context_properties props[3] = {CL_CONTEXT_PLATFORM,
                                      (cl_context_properties)platform, 0};

    clGetDeviceInfo(device, CL_DEVICE_NAME, sizeof(name), name, NULL);
    clGetPlatformInfo(platform, CL_PLATFORM_NAME, sizeof(pname), pname, NULL);
    state.context = clCreateContext(props, 1, &device, NULL, NULL, &err);
    if (err != CL_SUCCESS) {
        set_msg(msg, msglen, "clCreateContext failed on '%s' (%d)", name, err);
        return 1;
    }
    state.queue = clCreateCommandQueue(state.context, device, 0, &err);
    if (err == CL_SUCCESS)
        state.program = clCreateProgramWithSource(state.context, 1,
                                                  &kernel_source, &len, &err);
    if (err == CL_SUCCESS)
        err = clBuildProgram(state.program, 1, &device, "", NULL, NULL);
    if (err != CL_SUCCESS) {
        char log[4096] = "";

        if (state.program)
            clGetProgramBuildInfo(state.program, device, CL_PROGRAM_BUILD_LOG,
                                  sizeof(log), log, NULL);
        set_msg(msg, msglen, "OpenCL setup failed on '%s' (%d): %s", name, err,
                log);
        release_ocl();
        return 1;
    }
    state.kernel = clCreateKernel(state.program, "prepare", &err);
    if (err != CL_SUCCESS) {
        set_msg(msg, msglen, "clCreateKernel failed on '%s' (%d)", name, err);
        release_ocl();
        return 1;
    }
    state.use_ocl = 1;
    set_msg(msg, msglen, "OpenCL device '%s' (platform '%s')", name, pname);
    return 0;
}

static int try_type(cl_device_type type, const char *platform_opt, char *msg,
                    int msglen)
{
    cl_platform_id platforms[16];
    cl_device_id devices[16];
    cl_uint np = 0, nd, p, d;
    char pname[256];

    if (clGetPlatformIDs(16, platforms, &np) != CL_SUCCESS || np == 0) {
        set_msg(msg, msglen, "no OpenCL platform found");
        return 1;
    }
    set_msg(msg, msglen, "no matching OpenCL device found");
    for (p = 0; p < np; p++) {
        clGetPlatformInfo(platforms[p], CL_PLATFORM_NAME, sizeof(pname), pname,
                          NULL);
        if (platform_opt && !contains_nocase(pname, platform_opt))
            continue;
        if (clGetDeviceIDs(platforms[p], type, 16, devices, &nd) != CL_SUCCESS)
            continue;
        for (d = 0; d < nd; d++)
            if (try_device(platforms[p], devices[d], msg, msglen) == 0)
                return 0;
    }
    return 1;
}

int sarunwrap_init(const char *device, const char *platform, int nthreads,
                   char *msg, int msglen)
{
    const char *plat = (platform && *platform) ? platform : NULL;

    sarunwrap_finish();
    state.nthreads = nthreads;
    state.ready = 1;
    if (strcmp(device, "host") == 0) {
#ifdef _OPENMP
        set_msg(msg, msglen, "host CPU, %d OpenMP threads",
                nthreads > 0 ? nthreads : omp_get_max_threads());
#else
        set_msg(msg, msglen, "host CPU, single thread");
#endif
        return 0;
    }
    if (strcmp(device, "gpu") == 0 || strcmp(device, "auto") == 0) {
        if (try_type(CL_DEVICE_TYPE_GPU, plat, msg, msglen) == 0)
            return 0;
        if (strcmp(device, "gpu") == 0) {
            state.ready = 0;
            return 1;
        }
    }
    if (try_type(CL_DEVICE_TYPE_CPU, plat, msg, msglen) == 0)
        return 0;
    if (strcmp(device, "auto") == 0) {
        /* Fall back to OpenMP, keeping why OpenCL was not used. */
        char reason[1024] = "";
        size_t n;

        if (msg && msglen > 0)
            snprintf(reason, sizeof(reason), "%s", msg);
        sarunwrap_init("host", NULL, nthreads, msg, msglen);
        n = msg ? strlen(msg) : 0;
        if (msg && (int)n < msglen)
            snprintf(msg + n, (size_t)msglen - n, " (no OpenCL: %s)", reason);
        return 0;
    }
    state.ready = 0;
    return 1;
}

void sarunwrap_finish(void)
{
    release_ocl();
    state.use_ocl = 0;
    state.ready = 0;
}

struct graph {
    int rows, cols;
    long nloops;      /* (rows - 1) * (cols - 1); node nloops is the ground */
    float *dx, *wx;   /* rows * (cols - 1) horizontal gradients */
    float *dy, *wy;   /* (rows - 1) * cols vertical gradients */
    sarunwrap_s8 *q;  /* residues of the loops */
    int16_t *nx, *ny; /* integer cycle corrections of the gradients */
};

static int prepare_host(struct graph *g, const float *phase, const float *coh,
                        float looks)
{
    int i;

#ifdef _OPENMP
    if (state.nthreads > 0)
        omp_set_num_threads(state.nthreads);
#endif
#pragma omp parallel for schedule(static)
    for (i = 0; i < g->rows; i++) {
        int j;

        for (j = 0; j < g->cols; j++)
            sarunwrap_prep(i, j, g->rows, g->cols, phase, coh, looks, g->dx,
                           g->wx, g->dy, g->wy, g->q);
    }
    return 0;
}

static int prepare_ocl(struct graph *g, const float *phase, const float *coh,
                       float looks, char *msg, int msglen)
{
    size_t n = (size_t)g->rows * g->cols;
    size_t nxe = (size_t)g->rows * (g->cols - 1);
    size_t nye = (size_t)(g->rows - 1) * g->cols;
    size_t nq = (size_t)g->nloops;
    size_t gws[2], lws[2] = {16, 16};
    cl_mem b[7] = {0};
    cl_int err = CL_SUCCESS, e;
    int k, arg = 0, ret = 1;

    b[0] =
        clCreateBuffer(state.context, CL_MEM_READ_ONLY | CL_MEM_COPY_HOST_PTR,
                       n * sizeof(float), (void *)phase, &e);
    err |= e;
    b[1] =
        clCreateBuffer(state.context, CL_MEM_READ_ONLY | CL_MEM_COPY_HOST_PTR,
                       n * sizeof(float), (void *)coh, &e);
    err |= e;
    b[2] = clCreateBuffer(state.context, CL_MEM_WRITE_ONLY, nxe * sizeof(float),
                          NULL, &e);
    err |= e;
    b[3] = clCreateBuffer(state.context, CL_MEM_WRITE_ONLY, nxe * sizeof(float),
                          NULL, &e);
    err |= e;
    b[4] = clCreateBuffer(state.context, CL_MEM_WRITE_ONLY, nye * sizeof(float),
                          NULL, &e);
    err |= e;
    b[5] = clCreateBuffer(state.context, CL_MEM_WRITE_ONLY, nye * sizeof(float),
                          NULL, &e);
    err |= e;
    b[6] = clCreateBuffer(state.context, CL_MEM_WRITE_ONLY, nq, NULL, &e);
    err |= e;
    if (err != CL_SUCCESS) {
        set_msg(msg, msglen, "OpenCL buffer allocation failed");
        goto done;
    }
#define SETARG(v) err |= clSetKernelArg(state.kernel, arg++, sizeof(v), &(v))
    SETARG(g->rows);
    SETARG(g->cols);
    SETARG(b[0]);
    SETARG(b[1]);
    SETARG(looks);
    for (k = 2; k < 7; k++)
        SETARG(b[k]);
#undef SETARG
    gws[0] = (size_t)(g->cols + lws[0] - 1) / lws[0] * lws[0];
    gws[1] = (size_t)(g->rows + lws[1] - 1) / lws[1] * lws[1];
    if (err == CL_SUCCESS)
        err = clEnqueueNDRangeKernel(state.queue, state.kernel, 2, NULL, gws,
                                     lws, 0, NULL, NULL);
    if (err == CL_INVALID_WORK_GROUP_SIZE)
        err = clEnqueueNDRangeKernel(state.queue, state.kernel, 2, NULL, gws,
                                     NULL, 0, NULL, NULL);
    if (err == CL_SUCCESS)
        err = clEnqueueReadBuffer(state.queue, b[2], CL_TRUE, 0,
                                  nxe * sizeof(float), g->dx, 0, NULL, NULL);
    if (err == CL_SUCCESS)
        err = clEnqueueReadBuffer(state.queue, b[3], CL_TRUE, 0,
                                  nxe * sizeof(float), g->wx, 0, NULL, NULL);
    if (err == CL_SUCCESS)
        err = clEnqueueReadBuffer(state.queue, b[4], CL_TRUE, 0,
                                  nye * sizeof(float), g->dy, 0, NULL, NULL);
    if (err == CL_SUCCESS)
        err = clEnqueueReadBuffer(state.queue, b[5], CL_TRUE, 0,
                                  nye * sizeof(float), g->wy, 0, NULL, NULL);
    if (err == CL_SUCCESS)
        err = clEnqueueReadBuffer(state.queue, b[6], CL_TRUE, 0, nq, g->q, 0,
                                  NULL, NULL);
    if (err != CL_SUCCESS) {
        set_msg(msg, msglen, "OpenCL preparation failed (%d)", err);
        goto done;
    }
    ret = 0;
done:
    for (k = 0; k < 7; k++)
        if (b[k])
            clReleaseMemObject(b[k]);
    return ret;
}

/* One move of a unit of flow from a node to a neighbour: the neighbour,
 * the gradient it crosses (horizontal if is_x) and the change (+1 or -1)
 * of the integer correction of that gradient. */
struct move {
    long to;
    long edge;
    int is_x;
    int delta;
};

/* Moves out of loop u; returns their number (4). */
static int loop_moves(const struct graph *g, long u, struct move *m)
{
    int c1 = g->cols - 1;
    int i = (int)(u / c1), j = (int)(u % c1);
    long ground = g->nloops;

    /* Up, across the top gradient dx(i, j) (coefficient +1 in loop u). */
    m[0].to = i > 0 ? u - c1 : ground;
    m[0].edge = (long)i * c1 + j;
    m[0].is_x = 1;
    m[0].delta = -1;
    /* Down, across the bottom gradient dx(i + 1, j) (coefficient -1). */
    m[1].to = i < g->rows - 2 ? u + c1 : ground;
    m[1].edge = (long)(i + 1) * c1 + j;
    m[1].is_x = 1;
    m[1].delta = 1;
    /* Left, across the left gradient dy(i, j) (coefficient -1). */
    m[2].to = j > 0 ? u - 1 : ground;
    m[2].edge = (long)i * g->cols + j;
    m[2].is_x = 0;
    m[2].delta = 1;
    /* Right, across the right gradient dy(i, j + 1) (coefficient +1). */
    m[3].to = j < c1 - 1 ? u + 1 : ground;
    m[3].edge = (long)i * g->cols + j + 1;
    m[3].is_x = 0;
    m[3].delta = -1;
    return 4;
}

/* Moves out of the ground: the reverse of the loop moves into it. */
static long ground_moves(const struct graph *g, struct move *m)
{
    int c1 = g->cols - 1, i, j;
    long n = 0;

    for (j = 0; j < c1; j++) {
        m[n].to = j;
        m[n].edge = j;
        m[n].is_x = 1;
        m[n++].delta = 1;
        m[n].to = (long)(g->rows - 2) * c1 + j;
        m[n].edge = (long)(g->rows - 1) * c1 + j;
        m[n].is_x = 1;
        m[n++].delta = -1;
    }
    for (i = 0; i < g->rows - 1; i++) {
        m[n].to = (long)i * c1;
        m[n].edge = (long)i * g->cols;
        m[n].is_x = 0;
        m[n++].delta = -1;
        m[n].to = (long)i * c1 + c1 - 1;
        m[n].edge = (long)i * g->cols + g->cols - 1;
        m[n].is_x = 0;
        m[n++].delta = 1;
    }
    return n;
}

/* Statistical cost of changing the correction n of a gradient d by delta:
 * w ((d + 2 pi (n + delta))^2 - (d + 2 pi n)^2), never negative for the
 * first unit since |d| <= pi. */
static double move_cost(const struct graph *g, const struct move *m)
{
    float d = m->is_x ? g->dx[m->edge] : g->dy[m->edge];
    float w = m->is_x ? g->wx[m->edge] : g->wy[m->edge];
    int n = m->is_x ? g->nx[m->edge] : g->ny[m->edge];

    if (w == 0.0f)
        return 0.0;
    return 4.0 * M_PI * w * (m->delta * (d + 2.0 * M_PI * n) + M_PI);
}

struct heap {
    double *key;
    long *node;
    long size, cap;
};

static int heap_push(struct heap *h, double key, long node)
{
    long i;

    if (h->size == h->cap) {
        long cap = h->cap ? 2 * h->cap : 1024;
        double *k = realloc(h->key, cap * sizeof(double));
        long *n;

        if (!k)
            return 1;
        h->key = k;
        n = realloc(h->node, cap * sizeof(long));
        if (!n)
            return 1;
        h->node = n;
        h->cap = cap;
    }
    i = h->size++;
    while (i > 0 && h->key[(i - 1) / 2] > key) {
        h->key[i] = h->key[(i - 1) / 2];
        h->node[i] = h->node[(i - 1) / 2];
        i = (i - 1) / 2;
    }
    h->key[i] = key;
    h->node[i] = node;
    return 0;
}

static void heap_pop(struct heap *h, double *key, long *node)
{
    double k;
    long n, i = 0, c;

    *key = h->key[0];
    *node = h->node[0];
    k = h->key[--h->size];
    n = h->node[h->size];
    while ((c = 2 * i + 1) < h->size) {
        if (c + 1 < h->size && h->key[c + 1] < h->key[c])
            c++;
        if (h->key[c] >= k)
            break;
        h->key[i] = h->key[c];
        h->node[i] = h->node[c];
        i = c;
    }
    h->key[i] = k;
    h->node[i] = n;
}

/* Minimum cost flow from the positive residues to the negative ones and
 * the ground, by successive shortest paths (Dijkstra on reduced costs,
 * stopped at the first sink reached) with unit augmentations, which is
 * exact for these convex costs. */
static int solve_flow(struct graph *g, int64_t *stats, char *msg, int msglen)
{
    long nn = g->nloops + 1, ground = g->nloops, u, v, k, nlab;
    long nground;
    int *excess = malloc(nn * sizeof(int));
    double *pot = calloc(nn, sizeof(double));
    double *dist = malloc(nn * sizeof(double));
    int *stamp = calloc(nn, sizeof(int));
    int *settled = calloc(nn, sizeof(int));
    long *parent = malloc(nn * sizeof(long));
    struct move *pmove = malloc(nn * sizeof(struct move));
    long *labeled = malloc(nn * sizeof(long));
    struct move *gm =
        malloc(2 * ((long)g->rows + g->cols) * sizeof(struct move));
    struct heap heap = {NULL, NULL, 0, 0};
    long total = 0, residues = 0, paths = 0;
    int run = 0, ret = 1, largest = 0;

    if (!excess || !pot || !dist || !stamp || !settled || !parent || !pmove ||
        !labeled || !gm) {
        set_msg(msg, msglen, "out of memory for the flow network");
        goto done;
    }
    nground = ground_moves(g, gm);
    for (u = 0; u < g->nloops; u++) {
        excess[u] = g->q[u];
        total += g->q[u];
        residues += g->q[u] != 0;
    }
    excess[ground] = (int)-total;
    stats[0] = residues;

    for (u = 0; u < nn; u++) {
        while (excess[u] > 0) {
            long t = -1;
            double dt = 0.0;

            run++;
            heap.size = 0;
            nlab = 0;
            dist[u] = 0.0;
            stamp[u] = run;
            parent[u] = -1;
            labeled[nlab++] = u;
            if (heap_push(&heap, 0.0, u)) {
                set_msg(msg, msglen, "out of memory for the flow network");
                goto done;
            }
            while (heap.size > 0) {
                struct move lm[4], *moves;
                double d;
                long nm;

                heap_pop(&heap, &d, &v);
                if (settled[v] == run || d > dist[v])
                    continue;
                settled[v] = run;
                if (excess[v] < 0) {
                    t = v;
                    dt = d;
                    break;
                }
                if (v == ground) {
                    moves = gm;
                    nm = nground;
                }
                else {
                    moves = lm;
                    nm = loop_moves(g, v, lm);
                }
                for (k = 0; k < nm; k++) {
                    long w = moves[k].to;
                    double rc;

                    if (settled[w] == run)
                        continue;
                    rc = move_cost(g, &moves[k]) + pot[v] - pot[w];
                    if (rc < 0.0)
                        rc = 0.0; /* Rounding of the potentials. */
                    if (stamp[w] != run || d + rc < dist[w]) {
                        if (stamp[w] != run)
                            labeled[nlab++] = w;
                        stamp[w] = run;
                        dist[w] = d + rc;
                        parent[w] = v;
                        pmove[w] = moves[k];
                        if (heap_push(&heap, dist[w], w)) {
                            set_msg(msg, msglen,
                                    "out of memory for the flow network");
                            goto done;
                        }
                    }
                }
            }
            if (t < 0) {
                set_msg(msg, msglen, "flow network is disconnected");
                goto done;
            }
            /* Keep the reduced costs non-negative. */
            for (k = 0; k < nlab; k++) {
                v = labeled[k];
                if (dist[v] < dt)
                    pot[v] += dist[v] - dt;
            }
            /* Push one unit of flow along the path. */
            for (v = t; parent[v] >= 0; v = parent[v]) {
                int16_t *n = pmove[v].is_x ? &g->nx[pmove[v].edge]
                                           : &g->ny[pmove[v].edge];
                int a;

                *n += pmove[v].delta;
                a = abs(*n);
                if (a > largest)
                    largest = a;
            }
            excess[u]--;
            excess[t]++;
            paths++;
        }
    }
    stats[2] = paths;
    stats[3] = largest;
    ret = 0;

done:
    free(excess);
    free(pot);
    free(dist);
    free(stamp);
    free(settled);
    free(parent);
    free(pmove);
    free(labeled);
    free(gm);
    free(heap.key);
    free(heap.node);
    return ret;
}

/* Integrate the corrected gradients over each connected component of
 * non-null pixels (breadth first from its first pixel). */
static int integrate(const struct graph *g, const float *phase,
                     float *unwrapped, int32_t *component, int64_t *stats)
{
    long n = (long)g->rows * g->cols, p, head, tail;
    long *queue = malloc(n * sizeof(long));
    int32_t label = 0;
    int c1 = g->cols - 1;

    if (!queue)
        return 1;
    for (p = 0; p < n; p++) {
        component[p] = 0;
        unwrapped[p] = NAN;
    }
    for (p = 0; p < n; p++) {
        if (isnan(phase[p]) || component[p])
            continue;
        component[p] = ++label;
        unwrapped[p] = phase[p];
        head = tail = 0;
        queue[tail++] = p;
        while (head < tail) {
            long a = queue[head++], b;
            int i = (int)(a / g->cols), j = (int)(a % g->cols), k;

            for (k = 0; k < 4; k++) {
                double grad;

                if (k == 0 && j < g->cols - 1) {
                    b = a + 1;
                    grad = g->dx[(long)i * c1 + j] +
                           2.0 * M_PI * g->nx[(long)i * c1 + j];
                }
                else if (k == 1 && j > 0) {
                    b = a - 1;
                    grad = -(g->dx[(long)i * c1 + j - 1] +
                             2.0 * M_PI * g->nx[(long)i * c1 + j - 1]);
                }
                else if (k == 2 && i < g->rows - 1) {
                    b = a + g->cols;
                    grad = g->dy[a] + 2.0 * M_PI * g->ny[a];
                }
                else if (k == 3 && i > 0) {
                    b = a - g->cols;
                    grad = -(g->dy[b] + 2.0 * M_PI * g->ny[b]);
                }
                else
                    continue;
                if (isnan(phase[b]) || component[b])
                    continue;
                component[b] = label;
                unwrapped[b] = (float)(unwrapped[a] + grad);
                queue[tail++] = b;
            }
        }
    }
    stats[1] = label;
    free(queue);
    return 0;
}

int sarunwrap_run(struct sarunwrap_job *job, char *msg, int msglen)
{
    struct graph g;
    size_t nxe, nye;
    int ret = 1;

    if (!state.ready) {
        set_msg(msg, msglen, "sarunwrap_init() was not called");
        return 1;
    }
    if (job->rows < 2 || job->cols < 2) {
        set_msg(msg, msglen, "image too small (%dx%d)", job->rows, job->cols);
        return 1;
    }
    memset(&g, 0, sizeof(g));
    g.rows = job->rows;
    g.cols = job->cols;
    g.nloops = (long)(g.rows - 1) * (g.cols - 1);
    nxe = (size_t)g.rows * (g.cols - 1);
    nye = (size_t)(g.rows - 1) * g.cols;
    g.dx = malloc(nxe * sizeof(float));
    g.wx = malloc(nxe * sizeof(float));
    g.dy = malloc(nye * sizeof(float));
    g.wy = malloc(nye * sizeof(float));
    g.q = malloc((size_t)g.nloops);
    g.nx = calloc(nxe, sizeof(int16_t));
    g.ny = calloc(nye, sizeof(int16_t));
    if (!g.dx || !g.wx || !g.dy || !g.wy || !g.q || !g.nx || !g.ny) {
        set_msg(msg, msglen, "out of memory for %dx%d pixels", g.rows, g.cols);
        goto done;
    }
    memset(job->stats, 0, sizeof(job->stats));
    if (state.use_ocl) {
        if (prepare_ocl(&g, job->phase, job->coherence, job->looks, msg,
                        msglen))
            goto done;
    }
    else
        prepare_host(&g, job->phase, job->coherence, job->looks);
    if (solve_flow(&g, job->stats, msg, msglen))
        goto done;
    if (integrate(&g, job->phase, job->unwrapped, job->component, job->stats)) {
        set_msg(msg, msglen, "out of memory for the integration");
        goto done;
    }
    ret = 0;

done:
    free(g.dx);
    free(g.wx);
    free(g.dy);
    free(g.wy);
    free(g.q);
    free(g.nx);
    free(g.ny);
    return ret;
}
